version: "3.10"

services:
  backend:
    build: 
      context: ./backend
    env_file: ./backend/.env
    ports:
      - "8099:5001"
    environment:
      - OAUTHLIB_INSECURE_TRANSPORT="1"
      - AUTH_METADATA_URL="https://accounts.google.com/.well-known/openid-configuration"
      - AUTH_PUBLIC_KEY="https://www.googleapis.com/oauth2/v3/certs"
      - TODOIST_API_KEY
      - EVERHOUR_API_KEY
      - PIPEDRIVE_API_KEY
      - WORDPRESS_USER
      - WORDPRESS_PASS
  frontend:
    build:
      context: ./frontend
    ports:
      - "8098:3000"
    environment:
      - NEXTAUTH_SECRET="027grb120gbfc1328cygnfv130fvgcb30fvg30fvncg3r3444"
      - NEXTAUTH_URL=http://localhost:8098 
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - GOOGLE_CLIENT_ID=""
      - GOOGLE_CLIENT_SECRET=""
